version: "3"

services:
  mysql:
    image: "mysql:${DB_VER}"
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../data_model:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
