version: '3'

services:

  mysql:
    image: mysql:8.0.19
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../data_model:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movie_db
      MYSQL_USER: applicationuser
      MYSQL_PASSWORD: applicationuser
    ports:
      - "3306:3306"
